# db.yml

---
- name: FASE 2 | Configuración del Servidor de Base de Datos (PostgreSQL)
  hosts: dbservers
  become: true  # Usa el valor global, pero lo ponemos para claridad

  tasks:
    - name: (CLEANUP) Eliminar directorio temporal conflictivo para postgres
      ansible.builtin.file:
        path: /var/lib/postgresql/.ansible
        state: absent
      # Ejecutar como usuario 'root' para garantizar la eliminación
      become: true

    - name: 1. Instalar PostgreSQL y librería para Python
      ansible.builtin.apt:
        name: 
          - postgresql
          - python3-psycopg2 # Librería Python para interactuar con la DB
        state: present
        update_cache: yes
    
    - name: 2. Asegurar que PostgreSQL esté corriendo
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes
    
    - name: '3. Crear usuario de base de datos  (Ejemplo: app_user)' 
      ansible.builtin.postgresql_user:
        # Aquí usamos el usuario por defecto 'postgres' para ejecutar la tarea
        login_user: postgres
        name: app_user
        password: "secure_password_123"
        state: present
      # Especificamos que esta tarea se debe ejecutar como el usuario 'postgres' en el nodo remoto
      become_user: postgres
      
    - name: '4. Crear la base de datos de la aplicación (Ejemplo: app_db)'
      ansible.builtin.postgresql_db:
        login_user: postgres
        name: app_db
        owner: app_user
        encoding: UTF-8
        state: present
      become_user: postgres
