---
# requirements.yml
collections:
  - name: community.hashi_vault
    version: 6.1.0
  - name: community.general
    version: 8.6.0
  - name: ansible.utils
    version: 3.1.0
  - name: ansible.netcommon
    version: 6.1.0
  - name: community.docker
    version: 3.10.0
  - name: ansible.posix
    version: 1.6.0

  # - name: community.hashi_vault
  # version: 7.1.0
  #- name: community.general
  # version: 8.2.0